repos:
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        exclude: ^(tests|flowdapt/lib/database/migrate)/

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.0.1"
  #   hooks:
  #     - id: mypy
  #       exclude: ^(tests|flowdapt/lib/database/migrate)/
  #       args: [--ignore-missing-imports]

  # Use `pre-commit install --hook-type commit-msg` to enable commit-msg hooks.
  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.19.1"
    hooks:
      - id: gitlint